baseURL = "https://billy.dev/"
CanonifyUrls = true
languageCode = "en-us"
title = "Billy's Thoughts"
theme = "ezhil"

googleAnalytics = "UA-143355000-1"

[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.goldmark.extensions]
    footnote = true
    strikethrough = true
  [markup.goldmark.renderer]
    unsafe = true  # hack to allow <embed>

#  [markup.blackfriday]
#    hrefTargetBlank = true
#    fractions = false

[params]
  disableDisqusTypes = ["page", "posts"]
  # excludedTypes = ["recipes"]  # exclude these from all list.html pages

# menu
[[menu.main]]
name = "Start Here"
url = "/start-here"
weight = 1

[[menu.main]]
name = "Links"
url = "/links"
weight = 2

[[menu.main]]
name = "Blog"
url = "/posts"
weight = 3

[[menu.main]]
name = "Sabbatical Notes"
url = "/posts/sabbatical-notes"
weight = 4

# socials
[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/billyisyoung"

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/billyyoung/blog"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
   tag = "tags"
